# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField(verbose_name=False)),
                ('downloads', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField()),
                ('md5', models.CharField(max_length=32)),
                ('user_ip', models.CharField(default='255.255.255.0', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserGPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(max_length=200, null=True)),
                ('lng', models.CharField(max_length=15, null=True)),
                ('lat', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('quota', models.IntegerField(null=True)),
                ('use', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(max_length=200, null=True)),
                ('lng', models.CharField(max_length=15, null=True)),
                ('lat', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('quota', models.IntegerField(null=True)),
                ('use', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_by', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
