# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
