# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
